#!/usr/bin/env bash
# ============================================================================
# launch.sh — one-command Cloudflare Tunnel deployment for society-site.
#
# Prerequisites (one time only):
#   1. Install cloudflared: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/
#   2. cloudflared tunnel login     (opens browser; authorise your domain)
#   3. Set CLOUDFLARE_DOMAIN in .env or export it:
#        export CLOUDFLARE_DOMAIN=example.org
#
# Usage:
#   chmod +x launch.sh
#   ./launch.sh
#
# What it does:
#   - Creates a secure SECRET_KEY if you don't have one
#   - Installs Python deps with uv
#   - Starts gunicorn on 127.0.0.1:5005
#   - Creates (or reuses) a Cloudflare tunnel for your domain
#   - Routes traffic: yourdomain → tunnel → gunicorn
#   - Prints the setup URL when ready
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ------------------------------------------------------------------
# Colours
# ------------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}→${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC} $*"; }
err()   { echo -e "${RED}✗${NC} $*"; }

# ------------------------------------------------------------------
# 1. Prerequisites
# ------------------------------------------------------------------
for cmd in python3 uv cloudflared; do
  if ! command -v "$cmd" &>/dev/null; then
    err "$cmd is not installed or not in PATH."
    case "$cmd" in
      python3)  echo "   Install Python 3.12+ from https://python.org" ;;
      uv)       echo "   curl -LsSf https://astral.sh/uv/install.sh | sh" ;;
      cloudflared)
        echo "   Download from: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
        echo "   Then run: cloudflared tunnel login"
        ;;
    esac
    exit 1
  fi
done

info "All prerequisites found."

# ------------------------------------------------------------------
# 2. .env — create if missing
# ------------------------------------------------------------------
if [ ! -f .env ]; then
  info "No .env found — creating one with generated secrets."
  cat > .env <<EOF
# Generated by launch.sh — edit freely.
SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')
FLASK_ENV=production
EOF
  ok ".env created with a random SECRET_KEY."
else
  if ! grep -q '^SECRET_KEY=' .env || grep -q 'SECRET_KEY=dev-change-me' .env 2>/dev/null; then
    info "Generating a new SECRET_KEY in .env."
    if grep -q '^SECRET_KEY=' .env; then
      sed -i "s/^SECRET_KEY=.*/SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')/" .env
    else
      echo "SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')" >> .env
    fi
  fi
fi

# Export env so gunicorn and child processes pick it up
set -a; source .env; set +a

# ------------------------------------------------------------------
# 3. Domain
# ------------------------------------------------------------------
DOMAIN="${CLOUDFLARE_DOMAIN:-}"
if [ -z "$DOMAIN" ]; then
  info "No CLOUDFLARE_DOMAIN set."
  read -rp "  What domain do you want to use? (e.g. my-society.org): " DOMAIN
  if [ -z "$DOMAIN" ]; then
    err "A domain is required. Set CLOUDFLARE_DOMAIN=example.org in .env and re-run."
    exit 1
  fi
  if ! grep -q '^CLOUDFLARE_DOMAIN=' .env 2>/dev/null; then
    echo "CLOUDFLARE_DOMAIN=$DOMAIN" >> .env
  fi
fi

SUBDOMAIN="${CLOUDFLARE_SUBDOMAIN:-}"
TUNNEL_NAME="society-site-${DOMAIN//./-}"

# ------------------------------------------------------------------
# 4. Install Python deps
# ------------------------------------------------------------------
info "Syncing Python dependencies with uv…"
uv sync
ok "Dependencies ready."

# ------------------------------------------------------------------
# 5. Create project-local cloudflared state
# ------------------------------------------------------------------
CF_DIR="$SCRIPT_DIR/.cloudflared"
mkdir -p "$CF_DIR" "$SCRIPT_DIR/var"

# Copy origin cert if present in the default cloudflared location
if [ -f "$HOME/.cloudflared/cert.pem" ] && [ ! -f "$CF_DIR/cert.pem" ]; then
  cp "$HOME/.cloudflared/cert.pem" "$CF_DIR/cert.pem"
  ok "Copied Cloudflare origin certificate."
elif [ ! -f "$CF_DIR/cert.pem" ]; then
  err "No cert.pem found. Run 'cloudflared tunnel login' first."
  exit 1
fi

# ------------------------------------------------------------------
# 6. Create or reuse Cloudflare tunnel
# ------------------------------------------------------------------
TUNNEL_JSON="$CF_DIR/${TUNNEL_NAME}.json"

if [ ! -f "$TUNNEL_JSON" ]; then
  info "Creating Cloudflare tunnel: $TUNNEL_NAME"
  cloudflared tunnel create --credentials-file "$TUNNEL_JSON" "$TUNNEL_NAME"
  ok "Tunnel created."
else
  ok "Tunnel credentials found: $TUNNEL_NAME"
fi

# Write ingress config
PORT="${PORT:-5005}"
HOSTNAME="${SUBDOMAIN:+$SUBDOMAIN.$DOMAIN}"
HOSTNAME="${HOSTNAME:-$DOMAIN}"

cat > "$CF_DIR/config.yml" <<EOF
tunnel: $TUNNEL_NAME
credentials-file: $CF_DIR/${TUNNEL_NAME}.json

ingress:
  - hostname: $HOSTNAME
    service: http://127.0.0.1:$PORT
  - hostname: "*.$DOMAIN"
    service: http://127.0.0.1:$PORT
  - service: http_status:404
EOF

# ------------------------------------------------------------------
# 7. DNS routing
# ------------------------------------------------------------------
info "Setting up DNS: $HOSTNAME → tunnel"
cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$HOSTNAME" 2>/dev/null || true
if [ "$SUBDOMAIN" = "" ] || [ "$SUBDOMAIN" != "@" ]; then
  cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "www.$DOMAIN" 2>/dev/null || true
fi
ok "DNS routing configured."

# ------------------------------------------------------------------
# 8. Launch gunicorn in background
# ------------------------------------------------------------------
info "Starting gunicorn on 127.0.0.1:$PORT…"
uv run gunicorn \
  --bind "127.0.0.1:${PORT}" \
  --workers "${GUNICORN_WORKERS:-3}" \
  --threads "${GUNICORN_THREADS:-32}" \
  --worker-class gthread \
  --timeout 30 \
  --access-logfile - \
  --error-logfile - \
  wsgi:app &
GUNICORN_PID=$!
ok "gunicorn running (PID $GUNICORN_PID)."

# Cleanup on exit
trap 'info "Shutting down…"; kill $GUNICORN_PID 2>/dev/null; wait $GUNICORN_PID 2>/dev/null; ok "Done."' EXIT INT TERM

# Give gunicorn a moment
sleep 2

# ------------------------------------------------------------------
# 9. Run the tunnel
# ------------------------------------------------------------------
SETUP_PW_FILE="$SCRIPT_DIR/instance/setup-pw"
FIRST_RUN=false
if [ ! -f "$SCRIPT_DIR/instance/.setup-complete" ]; then
  FIRST_RUN=true
fi

echo ""
echo -e "${GREEN}══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Site is live!${NC}"
echo ""
echo -e "  URL:      ${CYAN}https://$HOSTNAME${NC}"
if $FIRST_RUN; then
  echo ""
  echo -e "  First run detected. Visit:"
  echo -e "  ${CYAN}https://$HOSTNAME/setup${NC}"
  if [ -f "$SETUP_PW_FILE" ]; then
    echo ""
    echo -e "  Setup password: $(cat "$SETUP_PW_FILE")"
  else
    echo ""
    echo -e "  Check gunicorn output above for the one-time setup password."
    echo -e "  (It is printed on first launch and saved to instance/setup-pw)"
  fi
fi
echo ""
echo -e "  Press Ctrl+C to stop."
echo -e "${GREEN}══════════════════════════════════════════════════════════${NC}"
echo ""

cloudflared tunnel --config "$CF_DIR/config.yml" run "$TUNNEL_NAME"
