"""add form schemas, custom data, sub events, form templates, early bird pricing

Revision ID: 1b5ead423541
Revises: bf3d1e8c2a90
Create Date: 2026-06-28 17:50:37.611854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5ead423541'
down_revision = 'bf3d1e8c2a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('conferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('hero_caption', sa.String(length=200), nullable=True),
    sa.Column('hero_image_filename', sa.String(length=255), nullable=True),
    sa.Column('hero_image_mode', sa.String(length=16), nullable=False),
    sa.Column('booklet_filename', sa.String(length=255), nullable=True),
    sa.Column('booklet_header_filename', sa.String(length=255), nullable=True),
    sa.Column('booklet_footer_filename', sa.String(length=255), nullable=True),
    sa.Column('booklet_background_filename', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('abstract_deadline', sa.Date(), nullable=True),
    sa.Column('early_bird_deadline', sa.Date(), nullable=True),
    sa.Column('registration_deadline', sa.Date(), nullable=True),
    sa.Column('max_abstracts_per_user', sa.Integer(), nullable=True),
    sa.Column('is_accepting_abstracts', sa.Boolean(), nullable=False),
    sa.Column('is_accepting_registrations', sa.Boolean(), nullable=False),
    sa.Column('abstracts_reopen_date', sa.Date(), nullable=True),
    sa.Column('registrations_reopen_date', sa.Date(), nullable=True),
    sa.Column('external_registration_url', sa.String(length=500), nullable=True),
    sa.Column('external_abstract_url', sa.String(length=500), nullable=True),
    sa.Column('tracks', sa.Text(), nullable=True),
    sa.Column('registration_form_schema', sa.JSON(), nullable=True),
    sa.Column('abstract_form_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conferences_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferences_slug'), ['slug'], unique=True)

    op.create_table('footer_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nav_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('open_in_new_tab', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_purpose'), ['purpose'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_slug'), ['slug'], unique=True)

    op.create_table('past_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('term_start', sa.Date(), nullable=True),
    sa.Column('term_end', sa.Date(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=240), nullable=True),
    sa.Column('intro_paragraph', sa.Text(), nullable=True),
    sa.Column('closing_statement', sa.Text(), nullable=True),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('browser_tab_title', sa.String(length=120), nullable=True),
    sa.Column('copyright_line', sa.String(length=240), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=True),
    sa.Column('currency_code', sa.String(length=8), nullable=True),
    sa.Column('currency_symbol', sa.String(length=4), nullable=True),
    sa.Column('payment_portal_enabled', sa.Boolean(), nullable=False),
    sa.Column('palette_page_bg', sa.String(length=24), nullable=True),
    sa.Column('palette_page_text', sa.String(length=24), nullable=True),
    sa.Column('palette_muted_text', sa.String(length=24), nullable=True),
    sa.Column('palette_link', sa.String(length=24), nullable=True),
    sa.Column('palette_link_hover', sa.String(length=24), nullable=True),
    sa.Column('palette_accent', sa.String(length=24), nullable=True),
    sa.Column('palette_accent_ink', sa.String(length=24), nullable=True),
    sa.Column('palette_header_bg', sa.String(length=24), nullable=True),
    sa.Column('palette_header_text', sa.String(length=24), nullable=True),
    sa.Column('palette_footer_bg', sa.String(length=24), nullable=True),
    sa.Column('palette_footer_text', sa.String(length=24), nullable=True),
    sa.Column('palette_card_bg', sa.String(length=24), nullable=True),
    sa.Column('palette_card_border', sa.String(length=24), nullable=True),
    sa.Column('palette_button_bg', sa.String(length=24), nullable=True),
    sa.Column('palette_button_text', sa.String(length=24), nullable=True),
    sa.Column('font_heading', sa.String(length=40), nullable=True),
    sa.Column('font_body', sa.String(length=40), nullable=True),
    sa.Column('font_link', sa.String(length=40), nullable=True),
    sa.Column('font_ui', sa.String(length=40), nullable=True),
    sa.Column('hero_image_filename', sa.String(length=255), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('favicon_filename', sa.String(length=255), nullable=True),
    sa.Column('og_image_filename', sa.String(length=255), nullable=True),
    sa.Column('board_term_start', sa.Date(), nullable=True),
    sa.Column('board_term_interval_months', sa.Integer(), nullable=True),
    sa.Column('board_last_archived_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footer_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('open_in_new_tab', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['footer_columns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('footer_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_footer_links_column_id'), ['column_id'], unique=False)

    op.create_table('organising_committee_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('affiliation', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('portrait_filename', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organising_committee_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organising_committee_members_conference_id'), ['conference_id'], unique=False)

    op.create_table('past_board_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('past_board_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('affiliation', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('orcid', sa.String(length=40), nullable=True),
    sa.Column('scholar_url', sa.String(length=400), nullable=True),
    sa.Column('website_url', sa.String(length=400), nullable=True),
    sa.Column('portrait_filename', sa.String(length=255), nullable=True),
    sa.Column('portrait_alt_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['past_board_id'], ['past_boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('past_board_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_past_board_members_past_board_id'), ['past_board_id'], unique=False)

    op.create_table('price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('early_bird_amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_tiers_conference_id'), ['conference_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.Column('permission_key', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name', 'permission_key', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_key'), ['permission_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_name'), ['role_name'], unique=False)

    op.create_table('sponsor_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsor_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsor_tiers_conference_id'), ['conference_id'], unique=False)

    op.create_table('sub_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('eligibility_note', sa.Text(), nullable=True),
    sa.Column('preference_schema', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_events_conference_id'), ['conference_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('affiliation', sa.String(length=200), nullable=True),
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_name'), ['role_name'], unique=False)

    op.create_table('abstracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('track', sa.String(length=120), nullable=True),
    sa.Column('presentation_type', sa.String(length=40), nullable=True),
    sa.Column('keywords', sa.String(length=300), nullable=True),
    sa.Column('coi', sa.Text(), nullable=True),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('figure_filename', sa.String(length=240), nullable=True),
    sa.Column('profile_picture_filename', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abstracts_conference_id'), ['conference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abstracts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_abstracts_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_kind', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.String(length=400), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('committee_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('affiliation', sa.String(length=200), nullable=True),
    sa.Column('dynamic_roles', sa.JSON(), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('orcid', sa.String(length=40), nullable=True),
    sa.Column('scholar_url', sa.String(length=400), nullable=True),
    sa.Column('website_url', sa.String(length=400), nullable=True),
    sa.Column('portrait_filename', sa.String(length=255), nullable=True),
    sa.Column('portrait_alt_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_contactable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('committee_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_committee_members_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_members_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_members_user_id'), ['user_id'], unique=False)

    op.create_table('form_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('tier_name', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('dietary', sa.String(length=200), nullable=True),
    sa.Column('accessibility', sa.String(length=400), nullable=True),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('sub_events', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('payment_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_conference_id'), ['conference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_user_id'), ['user_id'], unique=False)

    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['sponsor_tiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsors_tier_id'), ['tier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsors_tier_id'))

    op.drop_table('sponsors')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_registrations_conference_id'))

    op.drop_table('registrations')
    op.drop_table('form_templates')
    with op.batch_alter_table('committee_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committee_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_committee_members_display_order'))
        batch_op.drop_index(batch_op.f('ix_committee_members_deleted_at'))

    op.drop_table('committee_members')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abstracts_user_id'))
        batch_op.drop_index(batch_op.f('ix_abstracts_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_abstracts_conference_id'))

    op.drop_table('abstracts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('sub_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_events_conference_id'))

    op.drop_table('sub_events')
    with op.batch_alter_table('sponsor_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_tiers_conference_id'))

    op.drop_table('sponsor_tiers')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_name'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_key'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('price_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_tiers_conference_id'))

    op.drop_table('price_tiers')
    with op.batch_alter_table('past_board_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_past_board_members_past_board_id'))

    op.drop_table('past_board_members')
    with op.batch_alter_table('organising_committee_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organising_committee_members_conference_id'))

    op.drop_table('organising_committee_members')
    with op.batch_alter_table('footer_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_footer_links_column_id'))

    op.drop_table('footer_links')
    op.drop_table('site_settings')
    op.drop_table('roles')
    op.drop_table('past_boards')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_pages_deleted_at'))

    op.drop_table('pages')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_purpose'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_email'))

    op.drop_table('otp_codes')
    op.drop_table('nav_items')
    op.drop_table('footer_columns')
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conferences_slug'))
        batch_op.drop_index(batch_op.f('ix_conferences_deleted_at'))

    op.drop_table('conferences')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_deleted_at'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
