"""add registration_id to abstracts

Revision ID: 1da8cf69604f
Revises: 80b3d7969502
Create Date: 2026-07-02 17:44:29.593251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da8cf69604f'
down_revision = '80b3d7969502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_abstracts_registration_id'), ['registration_id'], unique=False)
        batch_op.create_foreign_key('fk_abstracts_registration_id', 'registrations', ['registration_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_abstracts_registration_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_abstracts_registration_id'))
        batch_op.drop_column('registration_id')

    # ### end Alembic commands ###
