"""add profile_picture to abstract

Revision ID: 2396d1a55dc0
Revises: 099d052323c0
Create Date: 2026-06-06 15:32:48.932617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2396d1a55dc0'
down_revision = '099d052323c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_filename', sa.String(length=240), nullable=True))

    with op.batch_alter_table('committee_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_contactable', sa.Boolean(), nullable=False))

    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_abstracts_per_user', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('max_abstracts_per_user')

    with op.batch_alter_table('committee_members', schema=None) as batch_op:
        batch_op.drop_column('is_contactable')

    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_filename')

    # ### end Alembic commands ###
