"""add presenting_author_index and references to abstract

Revision ID: 80b3d7969502
Revises: 1b5ead423541
Create Date: 2026-06-29 23:42:01.347499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b3d7969502'
down_revision = '1b5ead423541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presenting_author_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('references', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.drop_column('references')
        batch_op.drop_column('presenting_author_index')

    # ### end Alembic commands ###
