"""Initial schema

Revision ID: 9090345b3313
Revises: 
Create Date: 2026-05-29 22:02:12.414425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9090345b3313'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_accepting_abstracts', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_accepting_registrations', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('abstracts_reopen_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('registrations_reopen_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('external_registration_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('external_abstract_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('external_abstract_url')
        batch_op.drop_column('external_registration_url')
        batch_op.drop_column('registrations_reopen_date')
        batch_op.drop_column('abstracts_reopen_date')
        batch_op.drop_column('is_accepting_registrations')
        batch_op.drop_column('is_accepting_abstracts')
        batch_op.drop_column('registration_deadline')

    # ### end Alembic commands ###
