"""add payment gateway config and invoice template

Revision ID: 9c94e0ede9cc
Revises: f3a81c60d2e4
Create Date: 2026-07-17 15:00:52.890942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c94e0ede9cc'
down_revision = 'f3a81c60d2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('from_name', sa.String(length=120), nullable=True),
    sa.Column('from_email', sa.String(length=200), nullable=True),
    sa.Column('footer_text', sa.String(length=400), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_gateway_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_test_mode', sa.Boolean(), nullable=False),
    sa.Column('merchant_id', sa.String(length=120), nullable=True),
    sa.Column('api_key_id', sa.String(length=120), nullable=True),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('webhooks_key_id', sa.String(length=120), nullable=True),
    sa.Column('webhooks_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_set_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_warnings_sent', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_webhook_event', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('last_webhook_event')
        batch_op.drop_column('transaction_id')

    op.drop_table('payment_gateway_config')
    op.drop_table('invoice_template')
    # ### end Alembic commands ###
