"""add decline_reason to review_assignments

Revision ID: c8e588590700
Revises: e5e2069e85b0
Create Date: 2026-07-07 15:26:55.705610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e588590700'
down_revision = 'e5e2069e85b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decline_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_assignments', schema=None) as batch_op:
        batch_op.drop_column('decline_reason')

    # ### end Alembic commands ###
