"""Add intro_paragraph and intro_secondary to SiteSettings

Revision ID: d2cb373dbda9
Revises: d66d74816f94
Create Date: 2026-05-29 23:49:54.182797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cb373dbda9'
down_revision = 'd66d74816f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro_paragraph', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('intro_secondary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('intro_secondary')
        batch_op.drop_column('intro_paragraph')

    # ### end Alembic commands ###
