"""add review system models

Revision ID: e5e2069e85b0
Revises: 1da8cf69604f
Create Date: 2026-07-07 14:50:02.904916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e2069e85b0'
down_revision = '1da8cf69604f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expertise', sa.Text(), nullable=True),
    sa.Column('max_reviews', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conference_id', 'user_id', name='uq_conference_reviewer')
    )
    with op.batch_alter_table('conference_reviewers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conference_reviewers_conference_id'), ['conference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conference_reviewers_user_id'), ['user_id'], unique=False)

    op.create_table('review_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abstract_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('comments_author', sa.Text(), nullable=True),
    sa.Column('comments_chair', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstracts.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abstract_id', 'reviewer_id', name='uq_review_assignment')
    )
    with op.batch_alter_table('review_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_assignments_abstract_id'), ['abstract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_assignments_reviewer_id'), ['reviewer_id'], unique=False)

    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewers_per_paper', sa.Integer(), nullable=False, server_default='2'))
        batch_op.add_column(sa.Column('review_deadline', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('review_deadline')
        batch_op.drop_column('reviewers_per_paper')

    with op.batch_alter_table('review_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_assignments_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_review_assignments_abstract_id'))

    op.drop_table('review_assignments')
    with op.batch_alter_table('conference_reviewers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conference_reviewers_user_id'))
        batch_op.drop_index(batch_op.f('ix_conference_reviewers_conference_id'))

    op.drop_table('conference_reviewers')
    # ### end Alembic commands ###
