#!/usr/bin/env bash
# End-to-end launcher: gunicorn + Cloudflare tunnel.
#
# Every piece of tunnel state — per-tunnel credentials, ingress config,
# pidfile and logs — lives inside the project under .cloudflared/ and
# var/. We never touch ~/.cloudflared and never edit the user's global
# cloudflared config.
#
# Authentication ────────────────────────────────────────────────────────
# Two modes, in priority order:
#
#   1. CLOUDFLARE_API_TOKEN  (recommended)
#      A scoped API token created in the Cloudflare dashboard with
#      exactly these permissions:
#        Account  → Cloudflare Tunnel : Edit
#        Zone     → DNS              : Edit  (your-domain.example.org only)
#      Store it in .env.  If the VPS is compromised the attacker gets a
#      narrow-scope token — not your full Cloudflare account.
#
#   2. cert.pem               (legacy fallback)
#      Generated by `cloudflared tunnel login` and copied from
#      ~/.cloudflared/cert.pem.  WARNING: cert.pem grants FULL account
#      access.  Anyone who reads it can manage every domain and every
#      tunnel on your Cloudflare account.  Prefer the API token.
#
# cloudflared tunnel run does NOT need cert.pem or an API token — it
# authenticates the tunnel connection using only the per-tunnel
# credentials JSON file (--credentials-file).
# ────────────────────────────────────────────────────────────────────────
#
# Edit the four variables below, or set them as env vars before invoking.
set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-society-site}"
SUBDOMAIN="${SUBDOMAIN:-app}"
DOMAIN="${DOMAIN:-your-domain.example.org}"
PORT="${PORT:-5005}"
PROJECT="${PROJECT:-Society Site}"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$PROJECT_ROOT/.cloudflared"
RUN_DIR="$PROJECT_ROOT/var"
CONFIG_FILE="$CONFIG_DIR/config.yml"
ORIGIN_CERT="$CONFIG_DIR/cert.pem"
TUNNEL_CREDS="$CONFIG_DIR/$TUNNEL_NAME.json"
FLASK_LOG="$RUN_DIR/flask.log"
TUNNEL_LOG="$RUN_DIR/cloudflared.log"
FLASK_PIDFILE="$RUN_DIR/flask.pid"

mkdir -p "$CONFIG_DIR" "$RUN_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true
chmod 700 "$RUN_DIR" 2>/dev/null || true

# -----------------------------------------------------------------------
# Auth: detect available mode
# -----------------------------------------------------------------------
ENV_FILE="$PROJECT_ROOT/.env"

_detect_auth() {
    USE_API_TOKEN=""
    if [ -n "${CLOUDFLARE_API_TOKEN:-}" ]; then
        USE_API_TOKEN=1
    fi
}

_build_cfd() {
    if [ -n "$USE_API_TOKEN" ]; then
        echo "→ Auth: Cloudflare API token (scoped)"
        cfd() { cloudflared "$@"; }
    else
        echo "→ Auth: cert.pem  (WARNING: full account access — prefer CLOUDFLARE_API_TOKEN)"
        cfd() { cloudflared --origincert "$ORIGIN_CERT" "$@"; }
    fi
}

_save_token_to_env() {
    local token="$1"
    if [ ! -f "$ENV_FILE" ]; then
        printf 'CLOUDFLARE_API_TOKEN=%s\n' "$token" > "$ENV_FILE"
    elif grep -q '^CLOUDFLARE_API_TOKEN=' "$ENV_FILE" 2>/dev/null; then
        sed -i "s|^CLOUDFLARE_API_TOKEN=.*|CLOUDFLARE_API_TOKEN=$token|" "$ENV_FILE"
    elif grep -q '^# CLOUDFLARE_API_TOKEN=' "$ENV_FILE" 2>/dev/null; then
        sed -i "s|^# CLOUDFLARE_API_TOKEN=.*|CLOUDFLARE_API_TOKEN=$token|" "$ENV_FILE"
    else
        printf '\nCLOUDFLARE_API_TOKEN=%s\n' "$token" >> "$ENV_FILE"
    fi
}

_detect_auth

# Bootstrap cert.pem from ~/.cloudflared as a one-time convenience so
# existing setups aren't broken.  This ONLY fires when neither an API
# token nor a project-local cert.pem exist.
if [ -z "$USE_API_TOKEN" ] && [ ! -f "$ORIGIN_CERT" ]; then
    if [ -f "$HOME/.cloudflared/cert.pem" ]; then
        cp "$HOME/.cloudflared/cert.pem" "$ORIGIN_CERT"
        chmod 600 "$ORIGIN_CERT"
        echo "  copied origin cert from ~/.cloudflared/cert.pem (one-time)"
    fi
fi

# ---------- interactive token prompt (no auth at all yet) ---------------
if [ -z "$USE_API_TOKEN" ] && [ ! -f "$ORIGIN_CERT" ]; then
    if [ -t 0 ]; then
        cat >&2 << 'BANNER'

╔══════════════════════════════════════════════════════════════════╗
║  Cloudflare API token required                                  ║
║                                                                  ║
║  This script needs credentials to create and manage your         ║
║  Cloudflare tunnel.  A scoped API token is the safe choice.     ║
║                                                                  ║
║  To create one in 60 seconds:                                    ║
║                                                                  ║
║    1. Open the Cloudflare Dashboard                              ║
║       →  My Profile  →  API Tokens  →  Create Token              ║
║                                                                  ║
║    2. Choose  Create Custom Token  and set EXACTLY:              ║
║                                                                  ║
║       ┌──────────┬─────────────────────┬─────────────────────┐   ║
║       │ Scope    │ Permission          │ Resource            │   ║
║       ├──────────┼─────────────────────┼─────────────────────┤   ║
║       │ Account  │ Cloudflare Tunnel   │ Edit                │   ║
║       │ Zone     │ DNS                 │ Edit                │   ║
║       │          │                     │ (limit to your      │   ║
║       │          │                     │  domain only)       │   ║
║       └──────────┴─────────────────────┴─────────────────────┘   ║
║                                                                  ║
║    3. Copy the token (starts with a letter, ~40 chars).          ║
║                                                                  ║
║  Full step-by-step with screenshots:                             ║
║    docs/DEPLOY-CLOUDFLARE-SIMPLE.md                              ║
║                                                                  ║
║  Legacy alternative (NOT recommended):                           ║
║    Ctrl+C, run `cloudflared tunnel login`, re-run this script.   ║
║    This grants FULL Cloudflare account access to this machine.   ║
╚══════════════════════════════════════════════════════════════════╝
BANNER
        printf 'Cloudflare API token (paste it here): '
        read -r token </dev/tty
        if [ -n "$token" ]; then
            _save_token_to_env "$token"
            export CLOUDFLARE_API_TOKEN="$token"
            _detect_auth
            echo "  token saved to .env"
        else
            echo "  skipped — no token provided."
        fi
    fi
fi

# ---------- still nothing?  hard-fail with pointer to docs ------------
if [ -z "$USE_API_TOKEN" ] && [ ! -f "$ORIGIN_CERT" ]; then
    echo "✗ No Cloudflare credentials found." >&2
    echo "  Set CLOUDFLARE_API_TOKEN in .env (preferred) or run" >&2
    echo "  \`cloudflared tunnel login\` and re-run this script." >&2
    echo "  See docs/DEPLOY-CLOUDFLARE-SIMPLE.md for details." >&2
    exit 1
fi

_build_cfd

echo "→ $PROJECT (tunnel: $TUNNEL_NAME → $SUBDOMAIN.$DOMAIN, app: :$PORT)"
echo "  state dir: $CONFIG_DIR"

command -v cloudflared >/dev/null || {
    echo "✗ cloudflared not installed — see https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation/" >&2
    exit 1
}

# Create the tunnel if it doesn't exist.  --credentials-file keeps its
# JSON inside the project dir instead of ~/.cloudflared/<UUID>.json.
if ! cfd tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL_NAME"; then
    echo "  creating tunnel $TUNNEL_NAME (credentials → $TUNNEL_CREDS)"
    cfd tunnel create --credentials-file "$TUNNEL_CREDS" "$TUNNEL_NAME"
fi

if [ ! -f "$TUNNEL_CREDS" ]; then
    echo "✗ expected tunnel credentials at $TUNNEL_CREDS but none found." >&2
    echo "  the tunnel was probably created against ~/.cloudflared earlier." >&2
    echo "  either move its JSON in, or \`cfd tunnel delete $TUNNEL_NAME\` and rerun." >&2
    exit 1
fi
chmod 600 "$TUNNEL_CREDS"

# Project-local ingress config.  tunnel run only needs credentials-file;
# we include origincert only when using cert.pem mode (so tunnel run can
# auto-refresh edge registration if needed).
if [ -n "$USE_API_TOKEN" ]; then
    cat > "$CONFIG_FILE" << EOF
tunnel: $TUNNEL_NAME
credentials-file: $TUNNEL_CREDS
ingress:
  - hostname: $SUBDOMAIN.$DOMAIN
    service: http://localhost:$PORT
  - service: http_status:503
EOF
else
    cat > "$CONFIG_FILE" << EOF
tunnel: $TUNNEL_NAME
credentials-file: $TUNNEL_CREDS
origincert: $ORIGIN_CERT
ingress:
  - hostname: $SUBDOMAIN.$DOMAIN
    service: http://localhost:$PORT
  - service: http_status:503
EOF
fi

# --- launch gunicorn in the background -----------------------------------
"$PROJECT_ROOT/scripts/launch.sh" > "$FLASK_LOG" 2>&1 &
FLASK_PID=$!
echo $FLASK_PID > "$FLASK_PIDFILE"

cleanup() {
    if [ -f "$FLASK_PIDFILE" ]; then
        kill "$(cat "$FLASK_PIDFILE")" 2>/dev/null || true
        rm -f "$FLASK_PIDFILE"
    fi
}
trap cleanup EXIT INT TERM

sleep 2
if ! kill -0 "$FLASK_PID" 2>/dev/null; then
    echo "✗ gunicorn failed to start — see $FLASK_LOG" >&2
    exit 1
fi

# --- DNS route ------------------------------------------------------------
TUNNEL_ID=$(cfd tunnel list | awk -v n="$TUNNEL_NAME" '$2==n {print $1}')
cfd tunnel route dns --overwrite-dns "$TUNNEL_ID" "$SUBDOMAIN.$DOMAIN" || true

echo
echo "  Public:  https://$SUBDOMAIN.$DOMAIN"
echo "  Local:   http://localhost:$PORT"
echo "  Logs:    $FLASK_LOG / $TUNNEL_LOG"
echo "  Ctrl+C to stop."
echo

# tunnel run authenticates via --credentials-file — no cert or API token
# needed at the edge.
exec cfd --config "$CONFIG_FILE" tunnel run "$TUNNEL_NAME"
