#!/usr/bin/env bash
# End-to-end launcher: gunicorn + Cloudflare tunnel.
#
# Every piece of tunnel state — per-tunnel credentials, ingress config,
# pidfile and logs — lives inside the project under .cloudflared/ and
# var/. We never touch ~/.cloudflared and never edit the user's global
# cloudflared config.
#
# Authentication ────────────────────────────────────────────────────────
# Two modes, in priority order:
#
#   1. CLOUDFLARE_API_TOKEN  (recommended)
#      A scoped API token created in the Cloudflare dashboard with
#      exactly these permissions:
#        Account  → Cloudflare One Connector: cloudflared : Edit
#        Zone     → DNS              : Edit  (your-domain.example.org only)
#      Store it in .env.  If the VPS is compromised the attacker gets a
#      narrow-scope token — not your full Cloudflare account.
#
#   2. cert.pem               (legacy fallback)
#      Generated by `cloudflared tunnel login` and copied from
#      ~/.cloudflared/cert.pem.  WARNING: cert.pem grants FULL account
#      access.  Anyone who reads it can manage every domain and every
#      tunnel on your Cloudflare account.  Prefer the API token.
#
# cloudflared tunnel run does NOT need cert.pem or an API token — it
# authenticates the tunnel connection using only the per-tunnel
# credentials JSON file (--credentials-file).
# ────────────────────────────────────────────────────────────────────────
#
# Edit the four variables below, or set them as env vars before invoking.
set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-society-site}"
SUBDOMAIN="${SUBDOMAIN:-app}"
DOMAIN="${DOMAIN:-your-domain.example.org}"
PORT="${PORT:-5005}"
PROJECT="${PROJECT:-Society Site}"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$PROJECT_ROOT/.cloudflared"
RUN_DIR="$PROJECT_ROOT/var"
CONFIG_FILE="$CONFIG_DIR/config.yml"
ORIGIN_CERT="$CONFIG_DIR/cert.pem"
TUNNEL_CREDS="$CONFIG_DIR/$TUNNEL_NAME.json"
FLASK_LOG="$RUN_DIR/flask.log"
TUNNEL_LOG="$RUN_DIR/cloudflared.log"
FLASK_PIDFILE="$RUN_DIR/flask.pid"

mkdir -p "$CONFIG_DIR" "$RUN_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true
chmod 700 "$RUN_DIR" 2>/dev/null || true

echo "→ Conventus launcher starting..."
echo "  project root: $PROJECT_ROOT"

# -----------------------------------------------------------------------
# Interactive first-run setup  (prompts for core .env settings)
# -----------------------------------------------------------------------
ENV_FILE="$PROJECT_ROOT/.env"

_set_env() {
    local key="$1" val="$2" tmp="$ENV_FILE.tmp"
    if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
        sed "s|^${key}=.*|${key}=${val}|" "$ENV_FILE" > "$tmp" && mv "$tmp" "$ENV_FILE"
    elif grep -q "^# ${key}=" "$ENV_FILE" 2>/dev/null; then
        sed "s|^# ${key}=.*|${key}=${val}|" "$ENV_FILE" > "$tmp" && mv "$tmp" "$ENV_FILE"
    else
        cp "$ENV_FILE" "$tmp"
        printf '%s=%s\n' "$key" "$val" >> "$tmp"
        mv "$tmp" "$ENV_FILE"
    fi
}

_strip_quotes() {
    local val="$1"
    val="${val#\"}"; val="${val%\"}"
    val="${val#\'}"; val="${val%\'}"
    printf '%s' "$val"
}

_interactive_env_setup() {
    [ -t 0 ] || return 0
    echo "→ Checking configuration..."

    if [ ! -f "$ENV_FILE" ]; then
        echo "  .env not found — copying from .env.example"
        cp "$PROJECT_ROOT/.env.example" "$ENV_FILE"
    fi

    local cur_domain cur_token cur_secret cur_mail
    cur_domain="$(_strip_quotes "$(grep -E '^CLOUDFLARE_DOMAIN=' "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2-)")"
    cur_token="$(_strip_quotes "$(grep -E '^CLOUDFLARE_API_TOKEN=' "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2-)")"
    cur_secret="$(_strip_quotes "$(grep -E '^SECRET_KEY=' "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2-)")"
    cur_mail="$(_strip_quotes "$(grep -E '^MAIL_BACKEND=' "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2-)")"

    local placeholder_domain="your-domain.example.org"
    local placeholder_secret="CHANGE-ME-generate-with-secrets.token_urlsafe-48"

    local need=0
    if [ -z "$cur_domain" ] || [ "$cur_domain" = "$placeholder_domain" ]; then need=1; fi
    if [ -z "$cur_token" ]; then need=1; fi
    if [ -z "$cur_secret" ] || [ "$cur_secret" = "$placeholder_secret" ] || [[ "$cur_secret" == CHANGE-ME* ]]; then need=1; fi
    [ "$need" = 1 ] || { echo "  All core settings present — nothing to configure."; return 0; }

    cat << 'INTRO'

┌──────────────────────────────────────────────────────────────────┐
│                                                                  │
│  Conventus — first-run setup                                     │
│                                                                  │
│  Let's configure the essentials so everything works out of the   │
│  box.  Advanced settings use sensible defaults — you can edit    │
│  .env later to tweak them.                                       │
│                                                                  │
│  Press Enter to accept the [default] shown in brackets.          │
│                                                                  │
└──────────────────────────────────────────────────────────────────┘
INTRO

    if [ -z "$cur_secret" ] || [ "$cur_secret" = "$placeholder_secret" ] || [[ "$cur_secret" == CHANGE-ME* ]]; then
        local new_secret
        new_secret="$(python3 -c "import secrets; print(secrets.token_urlsafe(48))" 2>/dev/null \
                   || python -c "import secrets; print(secrets.token_urlsafe(48))" 2>/dev/null \
                   || openssl rand -base64 36 2>/dev/null)"
        if [ -n "$new_secret" ]; then
            _set_env "SECRET_KEY" "$new_secret"
            export SECRET_KEY="$new_secret"
            echo "  SECRET_KEY = (generated)"
        fi
    fi

    if [ -z "$cur_domain" ] || [ "$cur_domain" = "$placeholder_domain" ]; then
        printf '\nDomain your site will be served on\n  (e.g. your-society.example.org): '
        read -r new_domain </dev/tty || true
        if [ -n "$new_domain" ]; then
            _set_env "CLOUDFLARE_DOMAIN" "$new_domain"
            export CLOUDFLARE_DOMAIN="$new_domain"
            DOMAIN="$new_domain"
        fi
    fi

    printf 'Subdomain [app] (blank for apex, e.g. "www"): '
    read -r new_sub </dev/tty || true
    if [ -n "$new_sub" ]; then
        _set_env "CLOUDFLARE_SUBDOMAIN" "$new_sub"
        SUBDOMAIN="$new_sub"
    fi

    cur_token="$(_strip_quotes "$(grep -E '^CLOUDFLARE_API_TOKEN=' "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2-)")"
    if [ -z "$cur_token" ]; then
        cat << 'TOKENHELP'

  A Cloudflare API token lets this script create your tunnel and
  set up DNS without giving the VPS full account access.

  To create one: Cloudflare Dashboard → My Profile → API Tokens
  → Create Custom Token.  Set Account:Cloudflare One Connector:
  cloudflared:Edit and Zone:DNS:Edit (limit to your domain).
  Full walkthrough:
  docs/DEPLOY-CLOUDFLARE-SIMPLE.md

  (Press Enter to skip — you can also use cert.pem as a fallback.)
TOKENHELP
        printf 'Cloudflare API token: '
        read -r new_token </dev/tty || true
        if [ -n "$new_token" ]; then
            _set_env "CLOUDFLARE_API_TOKEN" "$new_token"
            export CLOUDFLARE_API_TOKEN="$new_token"
        fi
    fi

    echo ""
    echo "  Email delivery:"
    echo "    1. smtp    — send real emails (OTP login codes, contact form, alerts)"
    echo "    2. console — print to terminal (testing only — no real email delivery)"
    printf '  Choose [1/2, default: 1]: '
    read -r mail_choice </dev/tty || true
    mail_choice="${mail_choice:-1}"

    if [ "$mail_choice" = "1" ]; then
        _set_env "MAIL_BACKEND" "smtp"
        export MAIL_BACKEND="smtp"

        printf '  SMTP server hostname (e.g. smtp.gmail.com): '
        read -r val </dev/tty || true
        [ -n "$val" ] && { _set_env "SMTP_HOST" "$val"; export SMTP_HOST="$val"; }

        printf '  SMTP port [587]: '
        read -r val </dev/tty || true
        val="${val:-587}"
        _set_env "SMTP_PORT" "$val"
        export SMTP_PORT="$val"

        printf '  SMTP username: '
        read -r val </dev/tty || true
        [ -n "$val" ] && { _set_env "SMTP_USER" "$val"; export SMTP_USER="$val"; }

        printf '  SMTP password: '
        stty -echo 2>/dev/null || true
        read -r val </dev/tty || true
        stty echo 2>/dev/null || true
        echo ""
        [ -n "$val" ] && { _set_env "SMTP_PASS" "$val"; export SMTP_PASS="$val"; }

        local default_from="Name Your Society <noreply@${DOMAIN}>"
        printf '  From address ["%s"]: ' "$default_from"
        read -r val </dev/tty || true
        val="${val:-$default_from}"
        _set_env "MAIL_FROM" "$val"
        export MAIL_FROM="$val"
    else
        _set_env "MAIL_BACKEND" "console"
        export MAIL_BACKEND="console"
        echo "  Email set to console mode (no real delivery)."
    fi

    echo ""
    echo "  ✔  Settings saved to .env"
    echo ""
    echo "  Note: rate limiting uses in-process memory by default, which is"
    echo "  fine for single-workder or small deployments.  If you scale to"
    echo "  many gunicorn workers, set RATELIMIT_STORAGE_URI=redis://... in"
    echo "  .env to share limits across workers."
    echo ""
}

# Run setup before anything else (no-op if already configured)
_interactive_env_setup

# Load .env into the shell so cloudflared commands pick up the API token,
# domain, and other settings.  wsgi.py does the same for the Python side.
if [ -f "$ENV_FILE" ]; then
    set -a
    source "$ENV_FILE" 2>/dev/null || true
    set +a
fi

# Propagate values from .env to the local variables used throughout
# the rest of this script (ingress, DNS, tunnel name).
[ -n "${CLOUDFLARE_DOMAIN:-}" ]     && DOMAIN="$CLOUDFLARE_DOMAIN"
[ -n "${CLOUDFLARE_SUBDOMAIN:-}" ]  && SUBDOMAIN="$CLOUDFLARE_SUBDOMAIN"

# -----------------------------------------------------------------------
# Auth: detect available mode
# -----------------------------------------------------------------------

_detect_auth() {
    USE_API_TOKEN=""
    if [ -n "${CLOUDFLARE_API_TOKEN:-}" ]; then
        USE_API_TOKEN=1
    fi
}

_build_cfd() {
    if [ -n "$USE_API_TOKEN" ]; then
        echo "→ Auth: Cloudflare API token (scoped)"
        cfd() { cloudflared "$@"; }
    else
        echo "→ Auth: cert.pem  (WARNING: full account access — prefer CLOUDFLARE_API_TOKEN)"
        cfd() { cloudflared --origincert "$ORIGIN_CERT" "$@"; }
    fi
}

_detect_auth

# Bootstrap cert.pem from ~/.cloudflared as a one-time convenience so
# existing setups aren't broken.  This ONLY fires when neither an API
# token nor a project-local cert.pem exist.
if [ -z "$USE_API_TOKEN" ] && [ ! -f "$ORIGIN_CERT" ]; then
    if [ -f "$HOME/.cloudflared/cert.pem" ]; then
        cp "$HOME/.cloudflared/cert.pem" "$ORIGIN_CERT"
        chmod 600 "$ORIGIN_CERT"
        echo "  copied origin cert from ~/.cloudflared/cert.pem (one-time)"
    fi
fi

# ---------- last-resort token prompt (no auth at all yet) ---------------
if [ -z "$USE_API_TOKEN" ] && [ ! -f "$ORIGIN_CERT" ]; then
    if [ -t 0 ]; then
        cat << 'BANNER'

╔══════════════════════════════════════════════════════════════════╗
║  Cloudflare API token required                                  ║
║                                                                  ║
║  This script needs credentials to create and manage your         ║
║  Cloudflare tunnel.  A scoped API token is the safe choice.     ║
║                                                                  ║
║  To create one in 60 seconds:                                    ║
║                                                                  ║
║    1. Open the Cloudflare Dashboard                              ║
║       →  My Profile  →  API Tokens  →  Create Token              ║
║                                                                  ║
║    2. Choose  Create Custom Token  and set EXACTLY:              ║
║                                                                  ║
║       ┌──────────┬─────────────────────┬─────────────────────┐   ║
║       │ Scope    │ Permission          │ Resource            │   ║
║       ├──────────┼─────────────────────┼─────────────────────┤   ║
║       │ Account  │ Cloudflare One        │ Edit                │   ║
║       │          │ Connector: cloudflared│                     │   ║
║       │ Zone     │ DNS                 │ Edit                │   ║
║       │          │                     │ (limit to your      │   ║
║       │          │                     │  domain only)       │   ║
║       └──────────┴─────────────────────┴─────────────────────┘   ║
║                                                                  ║
║    3. Copy the token (starts with a letter, ~40 chars).          ║
║                                                                  ║
║  Full step-by-step can be found at:                             ║
║    docs/DEPLOY-CLOUDFLARE-SIMPLE.md                              ║
║                                                                  ║
║  Legacy alternative (NOT recommended):                           ║
║    Ctrl+C, run `cloudflared tunnel login`, re-run this script.   ║
║    This grants FULL Cloudflare account access to this machine.   ║
╚══════════════════════════════════════════════════════════════════╝
BANNER
        printf 'Cloudflare API token (paste it here): '
        read -r token </dev/tty || true
        if [ -n "$token" ]; then
            _set_env "CLOUDFLARE_API_TOKEN" "$token"
            export CLOUDFLARE_API_TOKEN="$token"
            _detect_auth
            echo "  token saved to .env"
        else
            echo "  skipped — no token provided."
        fi
    fi
fi

# ---------- still nothing?  hard-fail with pointer to docs ------------
if [ -z "$USE_API_TOKEN" ] && [ ! -f "$ORIGIN_CERT" ]; then
    echo "✗ No Cloudflare credentials found."
    echo "  Set CLOUDFLARE_API_TOKEN in .env (preferred) or run"
    echo "  \`cloudflared tunnel login\` and re-run this script."
    echo "  See docs/DEPLOY-CLOUDFLARE-SIMPLE.md for details."
    exit 1
fi

_build_cfd

echo "→ $PROJECT (tunnel: $TUNNEL_NAME → $SUBDOMAIN.$DOMAIN, app: :$PORT)"
echo "  state dir: $CONFIG_DIR"

command -v cloudflared >/dev/null || {
    echo "✗ cloudflared not installed — see https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation/" >&2
    exit 1
}

# Create the tunnel if it doesn't exist.  --credentials-file keeps its
# JSON inside the project dir instead of ~/.cloudflared/<UUID>.json.
if ! cfd tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL_NAME"; then
    echo "  creating tunnel $TUNNEL_NAME (credentials → $TUNNEL_CREDS)"
    cfd tunnel create --credentials-file "$TUNNEL_CREDS" "$TUNNEL_NAME"
fi

if [ ! -f "$TUNNEL_CREDS" ]; then
    echo "✗ expected tunnel credentials at $TUNNEL_CREDS but none found." >&2
    echo "  the tunnel was probably created against ~/.cloudflared earlier." >&2
    echo "  either move its JSON in, or \`cfd tunnel delete $TUNNEL_NAME\` and rerun." >&2
    exit 1
fi
chmod 600 "$TUNNEL_CREDS"

# Project-local ingress config.  tunnel run only needs credentials-file;
# we include origincert only when using cert.pem mode (so tunnel run can
# auto-refresh edge registration if needed).
if [ -n "$USE_API_TOKEN" ]; then
    cat > "$CONFIG_FILE" << EOF
tunnel: $TUNNEL_NAME
credentials-file: $TUNNEL_CREDS
ingress:
  - hostname: $SUBDOMAIN.$DOMAIN
    service: http://localhost:$PORT
  - service: http_status:503
EOF
else
    cat > "$CONFIG_FILE" << EOF
tunnel: $TUNNEL_NAME
credentials-file: $TUNNEL_CREDS
origincert: $ORIGIN_CERT
ingress:
  - hostname: $SUBDOMAIN.$DOMAIN
    service: http://localhost:$PORT
  - service: http_status:503
EOF
fi

# --- launch gunicorn in the background -----------------------------------
"$PROJECT_ROOT/scripts/launch.sh" > "$FLASK_LOG" 2>&1 &
FLASK_PID=$!
echo $FLASK_PID > "$FLASK_PIDFILE"

cleanup() {
    if [ -f "$FLASK_PIDFILE" ]; then
        kill "$(cat "$FLASK_PIDFILE")" 2>/dev/null || true
        rm -f "$FLASK_PIDFILE"
    fi
}
trap cleanup EXIT INT TERM

sleep 2
if ! kill -0 "$FLASK_PID" 2>/dev/null; then
    echo "✗ gunicorn failed to start — see $FLASK_LOG" >&2
    exit 1
fi

# --- DNS route ------------------------------------------------------------
TUNNEL_ID=$(cfd tunnel list | awk -v n="$TUNNEL_NAME" '$2==n {print $1}')
cfd tunnel route dns --overwrite-dns "$TUNNEL_ID" "$SUBDOMAIN.$DOMAIN" || true

echo
echo "  Public:  https://$SUBDOMAIN.$DOMAIN"
echo "  Local:   http://localhost:$PORT"
echo "  Logs:    $FLASK_LOG / $TUNNEL_LOG"
echo "  Ctrl+C to stop."
echo

# tunnel run authenticates via --credentials-file — no cert or API token
# needed at the edge.
exec cfd --config "$CONFIG_FILE" tunnel run "$TUNNEL_NAME"
