#!/usr/bin/env bash
# End-to-end launcher: gunicorn + Cloudflare tunnel.
#
# Every piece of tunnel state — per-tunnel credentials, ingress config,
# pidfile and logs — lives inside the project under .cloudflared/ and
# var/. We never touch ~/.cloudflared and never edit the user's global
# cloudflared config.
#
# Authentication ────────────────────────────────────────────────────────
# Two modes, in priority order:
#
#   1. CLOUDFLARE_API_TOKEN  (recommended)
#      A scoped API token created in the Cloudflare dashboard with
#      exactly these permissions:
#        Account  → Cloudflare Tunnel : Edit
#        Zone     → DNS              : Edit  (your-domain.example.org only)
#      Store it in .env.  If the VPS is compromised the attacker gets a
#      narrow-scope token — not your full Cloudflare account.
#
#   2. cert.pem               (legacy fallback)
#      Generated by `cloudflared tunnel login` and copied from
#      ~/.cloudflared/cert.pem.  WARNING: cert.pem grants FULL account
#      access.  Anyone who reads it can manage every domain and every
#      tunnel on your Cloudflare account.  Prefer the API token.
#
# cloudflared tunnel run does NOT need cert.pem or an API token — it
# authenticates the tunnel connection using only the per-tunnel
# credentials JSON file (--credentials-file).
# ────────────────────────────────────────────────────────────────────────
#
# Edit the four variables below, or set them as env vars before invoking.
set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-society-site}"
SUBDOMAIN="${SUBDOMAIN:-app}"
DOMAIN="${DOMAIN:-your-domain.example.org}"
PORT="${PORT:-5005}"
PROJECT="${PROJECT:-Society Site}"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$PROJECT_ROOT/.cloudflared"
RUN_DIR="$PROJECT_ROOT/var"
CONFIG_FILE="$CONFIG_DIR/config.yml"
ORIGIN_CERT="$CONFIG_DIR/cert.pem"
TUNNEL_CREDS="$CONFIG_DIR/$TUNNEL_NAME.json"
FLASK_LOG="$RUN_DIR/flask.log"
TUNNEL_LOG="$RUN_DIR/cloudflared.log"
FLASK_PIDFILE="$RUN_DIR/flask.pid"

mkdir -p "$CONFIG_DIR" "$RUN_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true
chmod 700 "$RUN_DIR" 2>/dev/null || true

# -----------------------------------------------------------------------
# Auth mode detection
# -----------------------------------------------------------------------
USE_API_TOKEN=""
if [ -n "${CLOUDFLARE_API_TOKEN:-}" ]; then
    USE_API_TOKEN=1
    echo "→ Auth: Cloudflare API token (scoped)"
else
    echo "→ Auth: cert.pem  (WARNING: full account access — prefer CLOUDFLARE_API_TOKEN)"
fi

# Build management-wrapper flags.  For API operations (create / list /
# route-dns) cloudflared reads CLOUDFLARE_API_TOKEN from the environment
# automatically; no extra flag needed.  For cert.pem mode we pass
# --origincert on every command.
if [ -n "$USE_API_TOKEN" ]; then
    cfd() { cloudflared "$@"; }
else
    cfd() { cloudflared --origincert "$ORIGIN_CERT" "$@"; }
fi

echo "→ $PROJECT (tunnel: $TUNNEL_NAME → $SUBDOMAIN.$DOMAIN, app: :$PORT)"
echo "  state dir: $CONFIG_DIR"

command -v cloudflared >/dev/null || {
    echo "✗ cloudflared not installed — see https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation/" >&2
    exit 1
}

# -----------------------------------------------------------------------
# Obtain authentication (cert.pem fallback only)
# -----------------------------------------------------------------------
if [ -z "$USE_API_TOKEN" ]; then
    if [ ! -f "$ORIGIN_CERT" ]; then
        if [ -f "$HOME/.cloudflared/cert.pem" ]; then
            cp "$HOME/.cloudflared/cert.pem" "$ORIGIN_CERT"
            chmod 600 "$ORIGIN_CERT"
            echo "  copied origin cert from ~/.cloudflared/cert.pem (one-time)"
        else
            echo "✗ no cert.pem in $CONFIG_DIR or ~/.cloudflared" >&2
            echo "  run \`cloudflared tunnel login\`, or set CLOUDFLARE_API_TOKEN in .env." >&2
            exit 1
        fi
    fi
fi

# Create the tunnel if it doesn't exist.  --credentials-file keeps its
# JSON inside the project dir instead of ~/.cloudflared/<UUID>.json.
if ! cfd tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL_NAME"; then
    echo "  creating tunnel $TUNNEL_NAME (credentials → $TUNNEL_CREDS)"
    cfd tunnel create --credentials-file "$TUNNEL_CREDS" "$TUNNEL_NAME"
fi

if [ ! -f "$TUNNEL_CREDS" ]; then
    echo "✗ expected tunnel credentials at $TUNNEL_CREDS but none found." >&2
    echo "  the tunnel was probably created against ~/.cloudflared earlier." >&2
    echo "  either move its JSON in, or \`cfd tunnel delete $TUNNEL_NAME\` and rerun." >&2
    exit 1
fi
chmod 600 "$TUNNEL_CREDS"

# Project-local ingress config.  tunnel run only needs credentials-file;
# we include origincert only when using cert.pem mode (so tunnel run can
# auto-refresh edge registration if needed).
if [ -n "$USE_API_TOKEN" ]; then
    cat > "$CONFIG_FILE" << EOF
tunnel: $TUNNEL_NAME
credentials-file: $TUNNEL_CREDS
ingress:
  - hostname: $SUBDOMAIN.$DOMAIN
    service: http://localhost:$PORT
  - service: http_status:503
EOF
else
    cat > "$CONFIG_FILE" << EOF
tunnel: $TUNNEL_NAME
credentials-file: $TUNNEL_CREDS
origincert: $ORIGIN_CERT
ingress:
  - hostname: $SUBDOMAIN.$DOMAIN
    service: http://localhost:$PORT
  - service: http_status:503
EOF
fi

# --- launch gunicorn in the background -----------------------------------
"$PROJECT_ROOT/scripts/launch.sh" > "$FLASK_LOG" 2>&1 &
FLASK_PID=$!
echo $FLASK_PID > "$FLASK_PIDFILE"

cleanup() {
    if [ -f "$FLASK_PIDFILE" ]; then
        kill "$(cat "$FLASK_PIDFILE")" 2>/dev/null || true
        rm -f "$FLASK_PIDFILE"
    fi
}
trap cleanup EXIT INT TERM

sleep 2
if ! kill -0 "$FLASK_PID" 2>/dev/null; then
    echo "✗ gunicorn failed to start — see $FLASK_LOG" >&2
    exit 1
fi

# --- DNS route ------------------------------------------------------------
TUNNEL_ID=$(cfd tunnel list | awk -v n="$TUNNEL_NAME" '$2==n {print $1}')
cfd tunnel route dns --overwrite-dns "$TUNNEL_ID" "$SUBDOMAIN.$DOMAIN" || true

echo
echo "  Public:  https://$SUBDOMAIN.$DOMAIN"
echo "  Local:   http://localhost:$PORT"
echo "  Logs:    $FLASK_LOG / $TUNNEL_LOG"
echo "  Ctrl+C to stop."
echo

# tunnel run authenticates via --credentials-file — no cert or API token
# needed at the edge.
exec cfd --config "$CONFIG_FILE" tunnel run "$TUNNEL_NAME"
